### ISSUE TITLE
Inaccurate description for move.usedTimes

### ISSUE THREAD

**Issue by jamesqo** [smogon/damage-calc#351]
Just noticed this recently:
```
4 Atk Life Orb Deoxys-Attack Superpower over 2 turns vs. 252 HP / 100 Def Muk-Alola: 351-414 (84.7 - 100%) -- 93.8% chance to 2HKO
```
I think this should read `93.8% to **not** 2HKO`, since the range is in Muk's favor to live.

**Comment by scheibo** [comment]
> 4 Atk Life Orb Deoxys-Attack Superpower over 2 turns vs. 252 HP / 100 Def Muk-Alola: 351-414 (84.7 - 100%) -- 6.3% chance to 2HKO
Possible damage amounts: (351, 356, 360, 364, 367, 371, 376, 379, 385, 389, 392, 397, 401, 405, 410, 414)

This perhas looks to now be correct? I believe letters fixed this in #369?
