### ISSUE TITLE
Body Press should use defence instead of attack

### ISSUE THREAD

**Issue by ajhyndman** [smogon/damage-calc#360]
The move "Body Press" should compute its damage using the defence stat instead of the attack stat of the attacker.

https://www.serebii.net/attackdex-swsh/bodypress.shtml

See also:

https://github.com/jake-white/VGC-Damage-Calculator/issues/78

**Comment by scheibo** [comment]
Didn't @AustinXII fix this with https://github.com/smogon/damage-calc/commit/b12e847ea5de861682854614883009577fbbafe9?

**Comment by kyleoliveiro** [comment]
> Didn't @AustinXII fix this with [b12e847](https://github.com/smogon/damage-calc/commit/b12e847ea5de861682854614883009577fbbafe9)?

That commit makes Body Press use ATK instead of DEF, and makes all other physical moves use DEF instead of ATK.

**Comment by AustinXII** [comment]
#361
