### ISSUE TITLE
Power Spot

### ISSUE THREAD

**Issue by Checkmate8397** [smogon/damage-calc#365]
So i just played a game, using stonjourner. The calcs show stonjourner getting a 1.3x damage boost to its attacks, but in the game it didn't as that isn't how Power Spot works. As i understand it, the ability should only apply to allies, so the calc is buffing the damage output incorrectly.

![image](https://user-images.githubusercontent.com/52177326/72226764-9a618f80-358c-11ea-9728-94c82def778b.png)
![image](https://user-images.githubusercontent.com/52177326/72226772-b9602180-358c-11ea-8151-9d1bc55be72e.png)

As a side note, i also noticed whilst taking these shots that selecting '(Other)' as the ability also buffs Stonjourners damage output.
![image](https://user-images.githubusercontent.com/52177326/72226782-ced54b80-358c-11ea-91eb-42607fcd34af.png)

**Comment by scheibo** [comment]
Looks like this was fixed in https://github.com/smogon/damage-calc/commit/5d8b11f538a35cb2937f468a30d5e3f423ab314a
