### ISSUE TITLE
Psychic Terrain calculating incorrectly

### ISSUE THREAD

**Issue by IllustriousMemories** [smogon/damage-calc#387]
The calc presented the following damage output:

![](https://media.discordapp.net/attachments/621082192088399882/698199989607989248/unknown.png)

+2 252 SpA Mewtwo Psystrike vs. 248 HP / 184+ Def Marvel Scale Milotic in Psychic Terrain: 331-391 (84.2 - 99.4%) -- guaranteed 2HKO after burn damage

However, when we tested it in a battle, the damage was consistently lower than 84% (we used a custom tier but we checked, the tier had no modifier to the terrain)
https://replay.pokemonshowdown.com/sports-gen8nationaldexpica-52529-hhqlxysyztnw2xq8e3r9y05lvgnkig9pw

At first I thought it was the tier messing up but I tested the calc on Trainer Tower (https://jake-white.github.io/VGC-Damage-Calculator/) and it returned the following:

![](https://media.discordapp.net/attachments/621082192088399882/698201100964331590/unknown.png)

This matched the damage output from our match, I ran the calc through Trainer Tower again but this time in USUM, it matched the damage from here, I believe that on the SWSH calc, it’s calculating terrain to be 1.5x still rather than 1.3x.

**Comment by scheibo** [comment]
![Screen Shot 2020-04-18 at 13 52 46](https://user-images.githubusercontent.com/117249/79671020-eb7cb300-817b-11ea-9952-2bf4bd81d425.png)

Confirmed VGC calc is correct here

**Comment by scheibo** [comment]
Thanks for your report! This should be fixed the next time we deploy
