### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by MagiaSN** [smogon/damage-calc#434]
Hi friends, I am going to write some code but find the unit tests keep failing. This is my current situation:

First, I pulled the latest commit, run `npm install` and then `npm test`, which reported 2 failures. One failure is because of data inconsistent with `@pkmn/dex` (some Max Moves do not have `breaksProtect` property in pkmn). The other is because the `bundle` script use wrong index in slicing. I can fix these and propose a pull request later.

Then, when I ran `npm test`, the tests were still failing. The error occurred when `bundle.test.ts` ran bundled code with `eval`, because the bundled code used relative imports (e.g. `require('./desc')`) but `bundle.test.ts` was not in the same directory as imported modules. I checked out the commit where the test is first committed, reinstalled all dependencies and the tests still failed. This test would never pass IMHO.

So could you show me how to get the tests passed? What am I missing?

**Comment by KrisXV** [comment]
Yes I was waiting until the end of March since I had already procrastinated so long but I’ll do one today

**Comment by AustinXII** [comment]
@MagiaSN also long time no see, glad to see you are still working on some calc related adventures. :)

**Comment by MagiaSN** [comment]
Waiting for your news :)

**Comment by monsanto** [comment]
Shouldn't be a problem anymore
