### ISSUE TITLE
Gen 3 badge boosts

### ISSUE THREAD

**Issue by wartab** [smogon/damage-calc#462]
Would it be okay if I added a flag for badge boosts that exist in Gen 3? I use this damage calc as a base for calculating damage for speedrun routing and the absence of this feature makes it basically impossible to use for that purpose. 

I could also attempt to implement it for Gen 2. For Gen 1, it's not particularly useful, cause badge boosts are completely broken there (surprise, surprise).

I realise the damage calc is mainly targetted at competitive Pokémon players, which does not make use of badge boosts, but it would be helpful for us.

**Comment by wartab** [comment]
In case you are unaware, Gen 1, Gen 2, and Gen 3 has a mechanic, where after obtaining certain badges, your stats are silently raised by 10% in Gen 3 and 12.5% in Gen 1 and 2.

**Comment by KrisXV** [comment]
Hey @wartab, really sorry for the late reply! I'd be fine with you adding a toggleable flag for this.

**Comment by monsanto** [comment]
Old issue, I don't know if this was implemented but if not & there is still interest feel free to send a PR.
