### ISSUE TITLE
Example of using @pkmn/data with @smogon/calc doesn't compile

### ISSUE THREAD

**Issue by grumpyotter** [smogon/damage-calc#465]
Hi, I'm new to Javascript and new to Github, so it's possible I'm missing something, but I wasn't able to get the example of using @pkmn/data and @smogon/calc together in README.md to compile (2nd snippet under Usage section) without making some updates.  The snippet currently reads...
```
import {Generations} from '@pkmn/data';
import {calculate, Pokemon, Move, Field} from '@smogon/calc/adaptable';

const gen = Generations.get(1);
const result = calculate(
  new Pokemon(gen, 'Gengar'),
  new Pokemon(gen. 'Vulpix'),
  new Move(gen, 'Surf'),
  new Field({defenderSide: {isLightScreen: true}})
);

```
I had to change it to the following to get it to compile.  The main issue I hit was that gen was missing from the arguments for calculate.  I also had to instantiate a new Generations object when using Generations from @pkmn/dex, although it's definitely possible that I'm just missing a better way to do that.  There was also a simple typo (period vs comma) in the Pokemon object instantiation fro Vulpix.  I also couldn't find @smogon/calc/adaptable, and had to point to the adaptable.js file.
```
import {Dex} from '@pkmn/dex';
import {Generations} from '@pkmn/data';
import {calculate, Pokemon, Move, Field} from '@smogon/calc/dist/adaptable.js';

const gens = new Generations(Dex)
const gen = gens.get(1)

const result = calculate(
  gen,
  new Pokemon(gen, 'Gengar'),
  new Pokemon(gen, 'Vulpix'),
  new Move(gen, 'Surf'),
  new Field({defenderSide: {isLightScreen: true}})
);
```

**Comment by monsanto** [comment]
Sorry nobody replied at the time, if you're still interested and having trouble feel free to reopen.
