### ISSUE TITLE
No option for pokemon staying level 50

### ISSUE THREAD

**Issue by YoshivsJoshi** [smogon/damage-calc#468]
Hello, this is the best damage calculator for everything but could you please add a feature to make all Pokémon permanently level 50 so when I'm in battle or just for ease of access if when I choose another set it auto sets the Pokémon to level 50, could you also add generic pokemon VGC 2022 sets, thank you very much!

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232965078-8c694158-0270-4700-b656-49b0297a14ee.png)
