### ISSUE TITLE
Generation 9

### ISSUE THREAD

**Issue by ajhyndman** [smogon/damage-calc#481]
Hi, I just wanted to raise my hand to offer to help with updates to this project for the upcoming Generation 9 release!

I'm not following any leaks, so I don't know how much change there will actually be.  Once we know how the mechanics work though, I think I might be able to help with the actual implementation.

Of course, if you think you have things under control, don't let me butt in.

**Comment by KrisXV** [comment]
We typically handle generation updates here after they're fully implemented (bar menial things) in PS, so after that's completed by the team working on that, I'll bump this to let you know.

**Comment by ajhyndman** [comment]
I'm just curious, do you expect to add Legends: Arceus species data to the Gen 8 patch, Gen 9 patch, or only include pokemon that make it to scarlet/violet?
