### ISSUE TITLE
Allow Calcs to be Shared

### ISSUE THREAD

**Issue by corydissinger** [smogon/damage-calc#499]
It's probably a good bit of work to allow calcs to be shared - but would it be possible using query params / path variables? Effectively a long URL with necessary state so people can share calcs.

**Comment by chessai** [comment]
Would love this.

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232965015-897c692b-60a6-4439-a186-7cde90ecad34.png)

**Comment by ForwardFeed** [comment]
Maybe using the import/export field is better,
Just adding a export calculation button and using the import field to just paste a Base64 or JSON Text

**Comment by ForwardFeed** [comment]
Well, i'm doing it, and nevermind i agree the path variable is the most practical for end user

**Comment by AustinXII** [comment]
Duplicate #586
