### ISSUE TITLE
Example in README doesn't work with gen 9

### ISSUE THREAD

**Issue by vs1720** [smogon/damage-calc#559]
Hi, the example in the readme with Chansey and Gengar doesn't work when generation is changed to gen 9 when running it as javascript with error: Cannot read properties of undefined (reading 'gengar')

I am using require instead of imports to run the code - const { calculate, Generations, Pokemon, Move } = require('@smogon/calc'); 

I have not really worked with javascript in the past so this could be just ignorance on my part but any help is appreciated!

**Comment by shrianshChari** [comment]
This is largely because the `@smogon/calc` package hasn't been updated to support gen 9 (see #503). As of now the package only supports gens 1-8, and if you try and use gen 9, then it'll show that there are no mons.

**Comment by thejetou** [comment]
v0.8.0 has since been released with Generation 9 support.
