### ISSUE TITLE
Feat: Calculate damage for Pain Split

### ISSUE THREAD

**Issue by jmynes** [smogon/damage-calc#572]
Is it possible to add Pain Split calculation?
It would be great to quickly see if I will heal or deal damage in any particular battle state, without having to manually do the math.

I'm not sure how this well fits in the official calculator's UI, but if damage healed/dealt were queryable, it would be easier to add to other software which queries this package.

----

If it were to fit into the existing UI, I would guess the best option is to put healing % on the left of the `-`, and dmg on the right, maybe with color coding, or a dotted underline indicating a tooltip?

**Comment by ForwardFeed** [comment]
Winning HP:
![image](https://github.com/smogon/damage-calc/assets/76596109/0dab4e0d-8e7b-47f2-bdf1-8cfae3b4af94)
Losing HP:
![image](https://github.com/smogon/damage-calc/assets/76596109/6f3124f6-f3c2-4325-94e0-67f4accbe0ee)

I managed to render this kind of results, if people feels its right so, i'll do a PR

**Comment by AustinXII** [comment]
#585
