### ISSUE TITLE
Set from previous generation appears in the list

### ISSUE THREAD

**Issue by Myvh** [smogon/damage-calc#577]
Steps to reproduce:

0. Load <https://calc.pokemonshowdown.com/> (the selected generation is S/V).
1. Look for Delphox.
2. In the set list, “1v1 Firium Z” appears, which is from generation VII.

I don’t know if it is specific to Delphox. If it is an intended behavior, I think it is not a good idea: showing a gen VII set while the selected generation is IX is misleading imo.

**Comment by shrianshChari** [comment]
Seems like this has been fixed

![image](https://github.com/smogon/damage-calc/assets/30420527/bcd171c9-95ff-4842-a911-4015b87f2224)

**Comment by shrianshChari** [comment]
This should no longer be relevant for the current time period since most Pokemon that are in generation 9 will have sets for them. However, for future reference, this is an intended feature.

https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9817470
