### ISSUE TITLE
Brendan SS Anne Pokemon missing

### ISSUE THREAD

**Issue by gabepen619** [smogon/damage-calc#594]
Seems like none of Brendan's SS Anne rival battle Pokemon have set profiles to do calcs against

**Comment by ShivaD173** [comment]
I think you left this on the wrong damage calculator. This is the main calculator for pokemon showdown, does not have any in-game fights.

**Comment by gabepen619** [comment]
Interesting bc I was on the radical Red dex and clicked a button to report
a bug! Oops, it's probably bc I got lost somewhere trying to figure out how
to submit the feedback LOL thanks

**Comment by ShivaD173** [comment]
You probably want this one then:
https://github.com/RadicalRedShowdown/damage-calc
