### ISSUE TITLE
Expose SETDEX in '@smogon/calc' npm package

### ISSUE THREAD

**Issue by cameronangliss** [smogon/damage-calc#622]
It would be useful for me to be able to access the `SETDEX`s for each generation so I could put the sets into the optional parameter when instantiating a `Pokemon` object. I saw that such a data structure exists in `shared_controls.js`. Would exposing that item in the `@smogon/calc` npm package be something people would be alright with?

**Comment by shrianshChari** [comment]
I do believe that [@pkmn/smogon](https://github.com/pkmn/smogon/tree/main/pkmn) provides APIs for looking at sets on the Smogon Dex, so that's probably also a good place to look.

**Comment by cameronangliss** [comment]
Ok, thanks!
