### ISSUE TITLE
Punching Glove 

### ISSUE THREAD

**Issue by AlexOn1ine** [smogon/damage-calc#665]
Punching Glove is [listed](https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts#L1226) under abilities. Is this correct? If you compare muscle band and punching glove in the calc the damage differs

**Comment by shrianshChari** [comment]
> Punching Glove is [listed](https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts#L1226) under abilities. Is this correct?

The line that you linked says `attacker.hasItem('Punching Glove')`, not `hasAbility`.

> If you compare muscle band and punching glove in the calc the damage differs

Are you using a punching move or a Pokemon with the ability Tough Claws? Punching Glove gives a 1.1x boost to punching moves but makes it not make contact, so if the damage boost is dependent on the move making contact (as Tough Claws is), then Muscle Band would deal more damage than Punching Glove. Additionally, if the move used isn't a punching move, then Muscle Band would give the boost, while Punching Glove wouldn't.

**Comment by AlexOn1ine** [comment]
I'm using the same set apart from the item
![image](https://github.com/user-attachments/assets/36354e34-ea2d-4138-81b5-a4d4ed6c8a7c)

**Comment by shrianshChari** [comment]
I see what the issue is; the Punching Glove gives a 4506 / 4096 boost, whereas the Muscle Band is a 4505 / 4096 boost. I'm not sure which is the correct boost for the both of them, but you're correct in that they should be the same number.

**Comment by urkerab** [comment]
Those are both the correct boosts according to Smogon researchers. See smogon/pokemon-showdown#9225 for the punching glove boost; the muscle band is a much older change.
